// NHL Fantasy Stat Categories Mapping
// Based on Yahoo Fantasy API stat_categories

export const NHL_STAT_CATEGORIES = {
  // Skater Stats
  GOALS: { id: 1, name: 'Goals', display: 'G', position: 'P' },
  ASSISTS: { id: 2, name: 'Assists', display: 'A', position: 'P' },
  POINTS: { id: 3, name: 'Points', display: 'P', position: 'P' },
  PLUS_MINUS: { id: 4, name: 'Plus/Minus', display: '+/-', position: 'P' },
  PENALTY_MINUTES: { id: 5, name: 'Penalty Minutes', display: 'PIM', position: 'P' },
  POWERPLAY_GOALS: { id: 6, name: 'Powerplay Goals', display: 'PPG', position: 'P' },
  POWERPLAY_ASSISTS: { id: 7, name: 'Powerplay Assists', display: 'PPA', position: 'P' },
  POWERPLAY_POINTS: { id: 8, name: 'Powerplay Points', display: 'PPP', position: 'P' },
  SHORTHANDED_GOALS: { id: 9, name: 'Shorthanded Goals', display: 'SHG', position: 'P' },
  SHORTHANDED_ASSISTS: { id: 10, name: 'Shorthanded Assists', display: 'SHA', position: 'P' },
  SHORTHANDED_POINTS: { id: 11, name: 'Shorthanded Points', display: 'SHP', position: 'P' },
  GAME_WINNING_GOALS: { id: 12, name: 'Game-Winning Goals', display: 'GWG', position: 'P' },
  GAME_TYING_GOALS: { id: 13, name: 'Game-Tying Goals', display: 'GTG', position: 'P' },
  SHOTS_ON_GOAL: { id: 14, name: 'Shots on Goal', display: 'SOG', position: 'P' },
  SHOOTING_PERCENTAGE: { id: 15, name: 'Shooting Percentage', display: 'SH%', position: 'P' },
  FACEOFFS_WON: { id: 16, name: 'Faceoffs Won', display: 'FW', position: 'P' },
  FACEOFFS_LOST: { id: 17, name: 'Faceoffs Lost', display: 'FL', position: 'P' },
  HITS: { id: 31, name: 'Hits', display: 'HIT', position: 'P' },
  BLOCKS: { id: 32, name: 'Blocks', display: 'BLK', position: 'P' },
  TIME_ON_ICE: { id: 33, name: 'Time on Ice', display: 'TOI', position: 'P' },
  AVERAGE_TIME_ON_ICE: { id: 34, name: 'Average Time on Ice', display: 'TOI/G', position: 'P' },

  // Goalie Stats
  GAMES_STARTED: { id: 18, name: 'Games Started', display: 'GS', position: 'G' },
  WINS: { id: 19, name: 'Wins', display: 'W', position: 'G' },
  LOSSES: { id: 20, name: 'Losses', display: 'L', position: 'G' },
  TIES: { id: 21, name: 'Ties', display: 'T', position: 'G' },
  GOALS_AGAINST: { id: 22, name: 'Goals Against', display: 'GA', position: 'G' },
  GOALS_AGAINST_AVERAGE: { id: 23, name: 'Goals Against Average', display: 'GAA', position: 'G' },
  SHOTS_AGAINST: { id: 24, name: 'Shots Against', display: 'SA', position: 'G' },
  SAVES: { id: 25, name: 'Saves', display: 'SV', position: 'G' },
  SAVE_PERCENTAGE: { id: 26, name: 'Save Percentage', display: 'SV%', position: 'G' },
  SHUTOUTS: { id: 27, name: 'Shutouts', display: 'SHO', position: 'G' },
  GOALIE_TIME_ON_ICE: { id: 28, name: 'Time on Ice', display: 'TOI', position: 'G' },

  // Games Played (both positions)
  GAMES_PLAYED: { id: 0, name: 'Games Played', display: 'GP', position: 'P,G' },
  F_D_GAMES: { id: 29, name: 'F/D Games', display: 'GP', position: 'P' },
  GOALIE_GAMES: { id: 30, name: 'Goalie Games', display: 'GP', position: 'G' },
} as const

// Hall of Fame Categories
export const HALL_OF_FAME_CATEGORIES = [
  {
    id: 'dynasty-builder',
    name: 'Dynasty Builder',
    description: 'Most total wins across all seasons',
    statType: 'wins',
    higherIsBetter: true,
  },
  {
    id: 'the-champion',
    name: 'The Champion',
    description: 'Most championships (first place finishes)',
    statType: 'rank',
    higherIsBetter: false, // Lower rank is better
  },
  {
    id: 'playoff-merchant',
    name: 'Playoff Merchant',
    description: 'Most playoff appearances',
    statType: 'playoffs',
    higherIsBetter: true,
  },
  {
    id: 'the-consistent-one',
    name: 'The Consistent One',
    description: 'Highest win percentage (min 2 seasons)',
    statType: 'winPercentage',
    higherIsBetter: true,
  },
  {
    id: 'point-machine',
    name: 'Point Machine',
    description: 'Most total fantasy points scored',
    statType: 'pointsFor',
    higherIsBetter: true,
  },
  {
    id: 'perfect-season',
    name: 'Perfect Season',
    description: 'Best single-season record',
    statType: 'record',
    higherIsBetter: true,
  },
  {
    id: 'scoring-explosion',
    name: 'Scoring Explosion',
    description: 'Highest fantasy points in a single season',
    statType: 'seasonPoints',
    higherIsBetter: true,
  },
  {
    id: 'runaway-winner',
    name: 'Runaway Winner',
    description: 'Biggest points margin above 2nd place',
    statType: 'margin',
    higherIsBetter: true,
  },
  {
    id: 'week-winner',
    name: 'Week Winner',
    description: 'Highest single-week fantasy score',
    statType: 'weeklyPoints',
    higherIsBetter: true,
  },
  {
    id: 'the-clutch-performer',
    name: 'The Clutch Performer',
    description: 'Most playoff week wins',
    statType: 'playoffWins',
    higherIsBetter: true,
  },
  {
    id: 'set-it-forget-it',
    name: 'Set It & Forget It',
    description: 'Fewest roster moves but still made playoffs',
    statType: 'efficiency',
    higherIsBetter: false, // Fewer moves is better
  },
  {
    id: 'the-steady-hand',
    name: 'The Steady Hand',
    description: 'Best record with fewest trades',
    statType: 'tradeEfficiency',
    higherIsBetter: false,
  },
  {
    id: 'brick-wall',
    name: 'Brick Wall',
    description: 'Most goalie wins',
    statType: 'goalieWins',
    statId: NHL_STAT_CATEGORIES.WINS.id,
    higherIsBetter: true,
  },
  {
    id: 'shutout-king',
    name: 'Shutout King',
    description: 'Most shutouts',
    statType: 'goalieShutouts',
    statId: NHL_STAT_CATEGORIES.SHUTOUTS.id,
    higherIsBetter: true,
  },
  {
    id: 'save-percentage-champion',
    name: 'Save % Champion',
    description: 'Highest save percentage',
    statType: 'goalieSavePercentage',
    statId: NHL_STAT_CATEGORIES.SAVE_PERCENTAGE.id,
    higherIsBetter: true,
  },
  {
    id: 'sniper',
    name: 'Sniper',
    description: 'Most goals scored',
    statType: 'skaterGoals',
    statId: NHL_STAT_CATEGORIES.GOALS.id,
    higherIsBetter: true,
  },
  {
    id: 'playmaker',
    name: 'Playmaker',
    description: 'Most assists',
    statType: 'skaterAssists',
    statId: NHL_STAT_CATEGORIES.ASSISTS.id,
    higherIsBetter: true,
  },
  {
    id: 'pp-specialist',
    name: 'PP Specialist',
    description: 'Most power play points',
    statType: 'skaterPPPoints',
    statId: NHL_STAT_CATEGORIES.POWERPLAY_POINTS.id,
    higherIsBetter: true,
  },
  {
    id: 'sh-hero',
    name: 'SH Hero',
    description: 'Most shorthanded goals',
    statType: 'skaterSHGoals',
    statId: NHL_STAT_CATEGORIES.SHORTHANDED_GOALS.id,
    higherIsBetter: true,
  },
  {
    id: 'the-enforcer',
    name: 'The Enforcer',
    description: 'Most penalty minutes but still won',
    statType: 'pimWithWins',
    statId: NHL_STAT_CATEGORIES.PENALTY_MINUTES.id,
    higherIsBetter: true,
  },
] as const

// Wall of Shame Categories
export const WALL_OF_SHAME_CATEGORIES = [
  {
    id: 'eternal-loser',
    name: 'Eternal Loser',
    description: 'Most total losses across all seasons',
    statType: 'losses',
    higherIsBetter: true,
  },
  {
    id: 'last-place-larry',
    name: 'Last Place Larry',
    description: 'Most last-place finishes',
    statType: 'lastPlace',
    higherIsBetter: true,
  },
  {
    id: 'the-unlucky-one',
    name: 'The Unlucky One',
    description: 'Most playoff misses (barely missed cutoff)',
    statType: 'playoffMisses',
    higherIsBetter: true,
  },
  {
    id: 'worst-record',
    name: 'Worst Record',
    description: 'Lowest single-season win percentage',
    statType: 'winPercentage',
    higherIsBetter: false,
  },
  {
    id: 'point-desert',
    name: 'Point Desert',
    description: 'Fewest fantasy points in a season',
    statType: 'pointsFor',
    higherIsBetter: false,
  },
  {
    id: 'rock-bottom',
    name: 'Rock Bottom',
    description: 'Lowest single-week fantasy score',
    statType: 'weeklyPoints',
    higherIsBetter: false,
  },
  {
    id: 'playoff-choke',
    name: 'Playoff Choke',
    description: 'Best regular season, worst playoff result',
    statType: 'choke',
    higherIsBetter: true,
  },
  {
    id: 'losing-streak',
    name: 'Losing Streak',
    description: 'Most consecutive losing weeks',
    statType: 'streak',
    higherIsBetter: true,
  },
  {
    id: 'waiver-warrior',
    name: 'Waiver Warrior',
    description: 'Most roster moves but still finished last',
    statType: 'inefficiency',
    higherIsBetter: true,
  },
  {
    id: 'the-overthinker',
    name: 'The Overthinker',
    description: 'Most trades but worst record',
    statType: 'tradeInefficiency',
    higherIsBetter: true,
  },
  {
    id: 'inactive-owner',
    name: 'Inactive Owner',
    description: 'Fewest moves, worst record',
    statType: 'inactivity',
    higherIsBetter: true,
  },
  {
    id: 'goalie-graveyard',
    name: 'Goalie Graveyard',
    description: 'Worst goalie stats',
    statType: 'goalieLosses',
    statId: NHL_STAT_CATEGORIES.LOSSES.id,
    higherIsBetter: true,
  },
  {
    id: 'cant-buy-a-goal',
    name: "Can't Buy a Goal",
    description: 'Lowest goals scored in season',
    statType: 'skaterGoals',
    statId: NHL_STAT_CATEGORIES.GOALS.id,
    higherIsBetter: false,
  },
  {
    id: 'penalty-box',
    name: 'Penalty Box',
    description: 'Most PIMs with losing record',
    statType: 'pimWithLosses',
    statId: NHL_STAT_CATEGORIES.PENALTY_MINUTES.id,
    higherIsBetter: true,
  },
  {
    id: 'the-minus',
    name: 'The Minus',
    description: 'Worst plus/minus rating',
    statType: 'skaterPlusMinus',
    statId: NHL_STAT_CATEGORIES.PLUS_MINUS.id,
    higherIsBetter: false,
  },
  {
    id: 'blowout-victim',
    name: 'Blowout Victim',
    description: 'Biggest single-week loss margin',
    statType: 'lossMargin',
    higherIsBetter: true,
  },
  {
    id: 'never-stood-a-chance',
    name: 'Never Stood a Chance',
    description: 'Lost most categories in one matchup',
    statType: 'categoryLosses',
    higherIsBetter: true,
  },
  {
    id: 'the-heartbreaker',
    name: 'The Heartbreaker',
    description: 'Most close losses (within 5 points)',
    statType: 'closeLosses',
    higherIsBetter: true,
  },
  {
    id: 'commissioner-fails',
    name: 'Commissioner Fails',
    description: "Commissioner's record vs league average",
    statType: 'commissionerCurse',
    higherIsBetter: true,
  },
  {
    id: 'cursed-team-name',
    name: 'Cursed Team Name',
    description: 'Worst performing team names over time',
    statType: 'teamNameCurse',
    higherIsBetter: true,
  },
] as const

// Game codes for different sports
export const GAME_CODES = {
  NHL: 419,
  NFL: 414,
  NBA: 418,
  MLB: 404,
} as const

// Position types
export const POSITION_TYPES = {
  PLAYER: 'P',
  GOALIE: 'G',
} as const
