// Static data for testing the new design
// This will be replaced with real API data later

export const staticLeagueData = {
  league: {
    name: "True Pride",
    season: "2022-23",
    numTeams: 12,
    isFinished: true,
  },
  teams: [
    {
      id: "1",
      name: "International Whiddens Day",
      managerNickname: "Manager1",
      rank: 1,
      wins: 18,
      losses: 4,
      ties: 2,
      pointsFor: 2456.8,
      pointsAgainst: 2103.2,
      winPercentage: 0.75,
    },
    {
      id: "2", 
      name: "Ice Cold Stunners",
      managerNickname: "Manager2",
      rank: 2,
      wins: 16,
      losses: 6,
      ties: 2,
      pointsFor: 2389.4,
      pointsAgainst: 2156.7,
      winPercentage: 0.67,
    },
    {
      id: "3",
      name: "Frozen Thunder",
      managerNickname: "Manager3", 
      rank: 3,
      wins: 15,
      losses: 7,
      ties: 2,
      pointsFor: 2298.1,
      pointsAgainst: 2189.3,
      winPercentage: 0.625,
    },
    {
      id: "4",
      name: "Blizzard Warriors",
      managerNickname: "Manager4",
      rank: 4,
      wins: 14,
      losses: 8,
      ties: 2,
      pointsFor: 2256.7,
      pointsAgainst: 2201.4,
      winPercentage: 0.583,
    },
    {
      id: "5",
      name: "Arctic Assassins",
      managerNickname: "Manager5",
      rank: 5,
      wins: 13,
      losses: 9,
      ties: 2,
      pointsFor: 2198.3,
      pointsAgainst: 2234.6,
      winPercentage: 0.542,
    },
    {
      id: "6",
      name: "Frostbite Flyers",
      managerNickname: "Manager6",
      rank: 6,
      wins: 12,
      losses: 10,
      ties: 2,
      pointsFor: 2156.9,
      pointsAgainst: 2267.8,
      winPercentage: 0.5,
    },
    {
      id: "7",
      name: "Ice Storm",
      managerNickname: "Manager7",
      rank: 7,
      wins: 11,
      losses: 11,
      ties: 2,
      pointsFor: 2103.4,
      pointsAgainst: 2298.1,
      winPercentage: 0.458,
    },
    {
      id: "8",
      name: "Frozen Fury",
      managerNickname: "Manager8",
      rank: 8,
      wins: 10,
      losses: 12,
      ties: 2,
      pointsFor: 2056.7,
      pointsAgainst: 2345.2,
      winPercentage: 0.417,
    },
    {
      id: "9",
      name: "Blizzard Blasters",
      managerNickname: "Manager9",
      rank: 9,
      wins: 9,
      losses: 13,
      ties: 2,
      pointsFor: 1987.3,
      pointsAgainst: 2398.6,
      winPercentage: 0.375,
    },
    {
      id: "10",
      name: "Ice Breakers",
      managerNickname: "Manager10",
      rank: 10,
      wins: 8,
      losses: 14,
      ties: 2,
      pointsFor: 1923.8,
      pointsAgainst: 2456.9,
      winPercentage: 0.333,
    },
    {
      id: "11",
      name: "Frost Giants",
      managerNickname: "Manager11",
      rank: 11,
      wins: 7,
      losses: 15,
      ties: 2,
      pointsFor: 1856.4,
      pointsAgainst: 2512.7,
      winPercentage: 0.292,
    },
    {
      id: "12",
      name: "Last Place Larrys",
      managerNickname: "Manager12",
      rank: 12,
      wins: 6,
      losses: 16,
      ties: 2,
      pointsFor: 1789.2,
      pointsAgainst: 2589.4,
      winPercentage: 0.25,
    },
  ],
  recentMatchups: [
    {
      id: "1",
      week: 25,
      season: "2022-23",
      homeTeam: "International Whiddens Day",
      awayTeam: "Ice Cold Stunners",
      homeTeamPoints: 98.7,
      awayTeamPoints: 89.3,
      winner: "International Whiddens Day",
      isPlayoffs: true,
    },
    {
      id: "2",
      week: 25,
      season: "2022-23", 
      homeTeam: "Frozen Thunder",
      awayTeam: "Blizzard Warriors",
      homeTeamPoints: 92.4,
      awayTeamPoints: 87.1,
      winner: "Frozen Thunder",
      isPlayoffs: true,
    },
    {
      id: "3",
      week: 24,
      season: "2022-23",
      homeTeam: "Arctic Assassins",
      awayTeam: "Frostbite Flyers",
      homeTeamPoints: 85.6,
      awayTeamPoints: 91.2,
      winner: "Frostbite Flyers",
      isPlayoffs: false,
    },
    {
      id: "4",
      week: 24,
      season: "2022-23",
      homeTeam: "Ice Storm",
      awayTeam: "Frozen Fury",
      homeTeamPoints: 88.9,
      awayTeamPoints: 84.3,
      winner: "Ice Storm",
      isPlayoffs: false,
    },
    {
      id: "5",
      week: 23,
      season: "2022-23",
      homeTeam: "Blizzard Blasters",
      awayTeam: "Ice Breakers",
      homeTeamPoints: 79.2,
      awayTeamPoints: 82.7,
      winner: "Ice Breakers",
      isPlayoffs: false,
    },
  ],
  hallOfFame: [
    {
      category: "The Champion",
      manager: "Manager1",
      teamName: "International Whiddens Day",
      value: 3,
      description: "3 Championships",
      season: "2022-23",
    },
    {
      category: "Dynasty Builder", 
      manager: "Manager1",
      teamName: "International Whiddens Day",
      value: 156,
      description: "156 Total Wins",
      season: "All Time",
    },
    {
      category: "Point Machine",
      manager: "Manager2",
      teamName: "Ice Cold Stunners", 
      value: 2456.8,
      description: "2456.8 Points in a Season",
      season: "2022-23",
    },
    {
      category: "Perfect Season",
      manager: "Manager1",
      teamName: "International Whiddens Day",
      value: 0.75,
      description: "18-4-2 (75%)",
      season: "2022-23",
    },
  ],
  wallOfShame: [
    {
      category: "Eternal Loser",
      manager: "Manager12",
      teamName: "Last Place Larrys",
      value: 89,
      description: "89 Total Losses",
      season: "All Time",
    },
    {
      category: "Last Place Larry",
      manager: "Manager12", 
      teamName: "Last Place Larrys",
      value: 4,
      description: "4 Last Place Finishes",
      season: "All Time",
    },
    {
      category: "Point Desert",
      manager: "Manager12",
      teamName: "Last Place Larrys",
      value: 1789.2,
      description: "1789.2 Points in a Season",
      season: "2022-23",
    },
    {
      category: "Rock Bottom",
      manager: "Manager12",
      teamName: "Last Place Larrys", 
      value: 0.25,
      description: "6-16-2 (25%)",
      season: "2022-23",
    },
  ],
  stats: {
    totalSeasons: 5,
    totalTeams: 12,
    totalMatchups: 840,
    currentSeason: "2022-23",
  }
}
