// Player rankings data extracted from MVP
// Future enhancement: Replace with API integration for yearly updates

import { Player } from '@/types/draft'

export const playerRankings: Player[] = [
  {rank: 1, name: "Connor McDavid", team: "EDM", pos: "C", avg: 1.6},
  {rank: 2, name: "Nathan MacKinnon", team: "COL", pos: "C", avg: 1.8},
  {rank: 3, name: "Nikita Kucherov", team: "TB", pos: "RW", avg: 3.0},
  {rank: 4, name: "Leon Draisaitl", team: "EDM", pos: "C,LW", avg: 3.6},
  {rank: 5, name: "David Pastrnak", team: "BOS", pos: "RW", avg: 5.4},
  {rank: 6, name: "Cale Makar", team: "COL", pos: "D", avg: 6.8},
  {rank: 7, name: "Kirill Kaprizov", team: "MIN", pos: "LW", avg: 7.4},
  {rank: 8, name: "Auston Matthews", team: "TOR", pos: "C", avg: 8.0},
  {rank: 9, name: "Connor Hellebuyck", team: "WPG", pos: "G", avg: 8.2},
  {rank: 10, name: "Mikko Rantanen", team: "DAL", pos: "LW,RW", avg: 10.6},
  {rank: 11, name: "Brady Tkachuk", team: "OTT", pos: "C,LW", avg: 11.6},
  {rank: 12, name: "Kyle Connor", team: "WPG", pos: "LW", avg: 13.4},
  {rank: 13, name: "William Nylander", team: "TOR", pos: "C,RW", avg: 14.0},
  {rank: 14, name: "Jack Eichel", team: "VGK", pos: "C", avg: 15.4},
  {rank: 15, name: "Artemi Panarin", team: "NYR", pos: "LW", avg: 15.6},
  {rank: 16, name: "Jack Hughes", team: "NJ", pos: "C,LW", avg: 16.6},
  {rank: 17, name: "Quinn Hughes", team: "VAN", pos: "D", avg: 17.6},
  {rank: 18, name: "Mitch Marner", team: "VGK", pos: "RW", avg: 18.6},
  {rank: 19, name: "Andrei Vasilevskiy", team: "TB", pos: "G", avg: 18.6},
  {rank: 20, name: "Brayden Point", team: "TB", pos: "C", avg: 21.6},
  {rank: 21, name: "Tage Thompson", team: "BUF", pos: "C,RW", avg: 22.6},
  {rank: 22, name: "Evan Bouchard", team: "EDM", pos: "D", avg: 23.8},
  {rank: 23, name: "Sam Reinhart", team: "FLA", pos: "C,RW", avg: 25.8},
  {rank: 24, name: "Jason Robertson", team: "DAL", pos: "LW,RW", avg: 25.8},
  {rank: 25, name: "Zach Werenski", team: "CBJ", pos: "D", avg: 27.8},
  {rank: 26, name: "Jake Guentzel", team: "TB", pos: "LW", avg: 28.2},
  {rank: 27, name: "Sidney Crosby", team: "PIT", pos: "C", avg: 28.4},
  {rank: 28, name: "Filip Forsberg", team: "NSH", pos: "LW", avg: 29.2},
  {rank: 29, name: "Jake Oettinger", team: "DAL", pos: "G", avg: 30.0},
  {rank: 30, name: "Clayton Keller", team: "UTA", pos: "LW,RW", avg: 30.2},
  {rank: 31, name: "Martin Necas", team: "COL", pos: "RW", avg: 31.4},
  {rank: 32, name: "Jesper Bratt", team: "NJ", pos: "LW,RW", avg: 34.6},
  {rank: 33, name: "Matt Boldy", team: "MIN", pos: "LW,RW", avg: 34.8},
  {rank: 34, name: "Igor Shesterkin", team: "NYR", pos: "G", avg: 35.2},
  {rank: 35, name: "Tim Stützle", team: "OTT", pos: "C,LW", avg: 35.2},
  {rank: 36, name: "Rasmus Dahlin", team: "BUF", pos: "D", avg: 36.0},
  {rank: 37, name: "Sergei Bobrovsky", team: "FLA", pos: "G", avg: 37.4},
  {rank: 38, name: "Brandon Hagel", team: "TB", pos: "LW,RW", avg: 37.6},
  {rank: 39, name: "Sebastian Aho", team: "CAR", pos: "C", avg: 39.0},
  {rank: 40, name: "J.T. Miller", team: "NYR", pos: "C,RW", avg: 39.0},
  {rank: 41, name: "Mark Scheifele", team: "WPG", pos: "C", avg: 41.8},
  {rank: 42, name: "Adrian Kempe", team: "LA", pos: "RW", avg: 42.0},
  {rank: 43, name: "Mackenzie Blackwood", team: "COL", pos: "G", avg: 44.8},
  {rank: 44, name: "Cole Caufield", team: "MTL", pos: "LW,RW", avg: 45.8},
  {rank: 45, name: "Nick Suzuki", team: "MTL", pos: "C", avg: 46.0},
  {rank: 46, name: "Wyatt Johnston", team: "DAL", pos: "C,RW", avg: 48.8},
  {rank: 47, name: "Matvei Michkov", team: "PHI", pos: "RW", avg: 50.6},
  {rank: 48, name: "Adam Fox", team: "NYR", pos: "D", avg: 50.6},
  {rank: 49, name: "Macklin Celebrini", team: "SJ", pos: "C", avg: 51.0},
  {rank: 50, name: "Alex Ovechkin", team: "WSH", pos: "LW,RW", avg: 51.6},
  {rank: 51, name: "Lucas Raymond", team: "DET", pos: "RW", avg: 53.2},
  {rank: 52, name: "Victor Hedman", team: "TB", pos: "D", avg: 54.4},
  {rank: 53, name: "Roman Josi", team: "NSH", pos: "D", avg: 55.8},
  {rank: 54, name: "Josh Morrissey", team: "WPG", pos: "D", avg: 58.6},
  {rank: 55, name: "Darcy Kuemper", team: "LA", pos: "G", avg: 59.0},
  {rank: 56, name: "Seth Jarvis", team: "CAR", pos: "C,LW,RW", avg: 59.0},
  {rank: 57, name: "Dylan Larkin", team: "DET", pos: "C", avg: 60.6},
  {rank: 58, name: "Travis Konecny", team: "PHI", pos: "LW,RW", avg: 60.8},
  {rank: 59, name: "Dylan Guenther", team: "UTA", pos: "RW", avg: 61.0},
  {rank: 60, name: "John Tavares", team: "TOR", pos: "C", avg: 62.8},
  {rank: 61, name: "Alex DeBrincat", team: "DET", pos: "LW,RW", avg: 63.6},
  {rank: 62, name: "Lane Hutson", team: "MTL", pos: "D", avg: 63.8},
  {rank: 63, name: "Connor Bedard", team: "CHI", pos: "C,RW", avg: 64.4},
  {rank: 64, name: "Kevin Fiala", team: "LA", pos: "LW", avg: 66.4},
  {rank: 65, name: "Nico Hischier", team: "NJ", pos: "C", avg: 68.8},
  {rank: 66, name: "Jordan Kyrou", team: "STL", pos: "RW", avg: 69.6},
  {rank: 67, name: "Adin Hill", team: "VGK", pos: "G", avg: 69.8},
  {rank: 68, name: "Robert Thomas", team: "STL", pos: "C", avg: 70.2},
  {rank: 69, name: "Filip Gustavsson", team: "MIN", pos: "G", avg: 72.2},
  {rank: 70, name: "Mika Zibanejad", team: "NYR", pos: "C,RW", avg: 72.4},
  {rank: 71, name: "Elias Pettersson", team: "VAN", pos: "C,LW", avg: 74.4},
  {rank: 72, name: "Matthew Knies", team: "TOR", pos: "LW", avg: 74.6},
  {rank: 73, name: "Roope Hintz", team: "DAL", pos: "C", avg: 74.8},
  {rank: 74, name: "Kirill Marchenko", team: "CBJ", pos: "RW", avg: 75.8},
  {rank: 75, name: "Nazem Kadri", team: "CGY", pos: "C", avg: 78.2},
  {rank: 76, name: "Carter Verhaeghe", team: "FLA", pos: "LW", avg: 79.2},
  {rank: 77, name: "Shea Theodore", team: "VGK", pos: "D", avg: 79.6},
  {rank: 78, name: "Dustin Wolf", team: "CGY", pos: "G", avg: 81.0},
  {rank: 79, name: "Andrei Svechnikov", team: "CAR", pos: "LW,RW", avg: 84.4},
  {rank: 80, name: "JJ Peterka", team: "UTA", pos: "LW,RW", avg: 85.6},
  {rank: 81, name: "Nikolaj Ehlers", team: "CAR", pos: "LW,RW", avg: 85.6},
  {rank: 82, name: "Jake Sanderson", team: "OTT", pos: "D", avg: 87.0},
  {rank: 83, name: "Mackenzie Weegar", team: "CGY", pos: "D", avg: 87.4},
  {rank: 84, name: "Anthony Stolarz", team: "TOR", pos: "G", avg: 91.0},
  {rank: 85, name: "Alex Tuch", team: "BUF", pos: "RW", avg: 91.8},
  {rank: 86, name: "Logan Thompson", team: "WSH", pos: "G", avg: 92.8},
  {rank: 87, name: "Jacob Markstrom", team: "NJ", pos: "G", avg: 93.2},
  {rank: 88, name: "Ilya Sorokin", team: "NYI", pos: "G", avg: 93.4},
  {rank: 89, name: "Linus Ullmark", team: "OTT", pos: "G", avg: 94.0},
  {rank: 90, name: "Valeri Nichushkin", team: "COL", pos: "LW,RW", avg: 96.0},
  {rank: 91, name: "Adam Fantilli", team: "CBJ", pos: "C", avg: 96.2},
  {rank: 92, name: "Dougie Hamilton", team: "NJ", pos: "D", avg: 96.6},
  {rank: 93, name: "Pavel Dorofeyev", team: "VGK", pos: "LW,RW", avg: 97.4},
  {rank: 94, name: "Vincent Trocheck", team: "NYR", pos: "C", avg: 99.2},
  {rank: 95, name: "Stuart Skinner", team: "EDM", pos: "G", avg: 100.2},
  {rank: 96, name: "Drake Batherson", team: "OTT", pos: "LW,RW", avg: 100.6},
  {rank: 97, name: "Tom Wilson", team: "WSH", pos: "RW", avg: 101.2},
  {rank: 98, name: "Dylan Holloway", team: "STL", pos: "C,LW", avg: 102.8},
  {rank: 99, name: "Logan Cooley", team: "UTA", pos: "C", avg: 103.6},
  {rank: 100, name: "Juuse Saros", team: "NSH", pos: "G", avg: 103.6},
  {rank: 101, name: "Quinton Byfield", team: "LA", pos: "C,LW", avg: 105.0},
  {rank: 102, name: "Timo Meier", team: "NJ", pos: "LW,RW", avg: 106.0},
  {rank: 103, name: "Cutter Gauthier", team: "ANA", pos: "C,LW", avg: 107.0},
  {rank: 104, name: "Bo Horvat", team: "NYI", pos: "C", avg: 108.0},
  {rank: 105, name: "Moritz Seider", team: "DET", pos: "D", avg: 109.0},
  {rank: 106, name: "Leo Carlsson", team: "ANA", pos: "C", avg: 110.0},
  {rank: 107, name: "Miro Heiskanen", team: "DAL", pos: "D", avg: 111.0},
  {rank: 108, name: "Matthew Tkachuk", team: "FLA", pos: "LW,RW", avg: 112.0},
  {rank: 109, name: "Aliaksei Protas", team: "WSH", pos: "C,LW,RW", avg: 113.0},
  {rank: 110, name: "Juraj Slafkovsky", team: "MTL", pos: "LW", avg: 114.0},
  {rank: 111, name: "Dylan Strome", team: "WSH", pos: "C,LW", avg: 115.0},
  {rank: 112, name: "Thomas Harley", team: "DAL", pos: "D", avg: 116.0},
  {rank: 113, name: "Juraj Slafkovsky", team: "MTL", pos: "LW,RW", avg: 104.8},
  {rank: 114, name: "Zach Hyman", team: "EDM", pos: "LW,RW", avg: 104.8},
  {rank: 115, name: "Joel Eriksson Ek", team: "MIN", pos: "C", avg: 105.8},
  {rank: 116, name: "Dylan Strome", team: "WSH", pos: "C", avg: 106.0},
  {rank: 117, name: "Timo Meier", team: "NJ", pos: "LW,RW", avg: 106.4},
  {rank: 118, name: "Quinton Byfield", team: "LA", pos: "C,LW", avg: 106.6},
  {rank: 119, name: "Sam Montembeault", team: "MTL", pos: "G", avg: 107.0},
  {rank: 120, name: "Bo Horvat", team: "NYI", pos: "C", avg: 109.0},
  {rank: 121, name: "Jordan Binnington", team: "STL", pos: "G", avg: 110.4},
  {rank: 122, name: "Matthew Tkachuk", team: "FLA", pos: "LW,RW", avg: 111.2},
  {rank: 123, name: "Thomas Harley", team: "DAL", pos: "D", avg: 111.6},
  {rank: 124, name: "Moritz Seider", team: "DET", pos: "D", avg: 111.8},
  {rank: 125, name: "Mathew Barzal", team: "NYI", pos: "C,RW", avg: 112.8},
  {rank: 126, name: "Mikhail Sergachev", team: "UTA", pos: "D", avg: 119.0},
  {rank: 127, name: "Jared McCann", team: "SEA", pos: "C,LW", avg: 122.8},
  {rank: 128, name: "Sam Bennett", team: "FLA", pos: "C", avg: 123.2},
  {rank: 129, name: "Rickard Rakell", team: "PIT", pos: "C,LW,RW", avg: 124.6},
  {rank: 130, name: "Matt Duchene", team: "DAL", pos: "C,RW", avg: 125.0},
  {rank: 131, name: "Miro Heiskanen", team: "DAL", pos: "D", avg: 125.8},
  {rank: 132, name: "Mark Stone", team: "VGK", pos: "RW", avg: 127.0},
  {rank: 133, name: "Gabriel Vilardi", team: "WPG", pos: "C,RW", avg: 128.8},
  {rank: 134, name: "Karel Vejmelka", team: "UTA", pos: "G", avg: 129.2},
  {rank: 135, name: "Bryan Rust", team: "PIT", pos: "RW", avg: 129.6},
  {rank: 136, name: "Ivan Demidov", team: "MTL", pos: "RW", avg: 129.8},
  {rank: 137, name: "Frederik Andersen", team: "CAR", pos: "G", avg: 130.4},
  {rank: 138, name: "Pyotr Kochetkov", team: "CAR", pos: "G", avg: 130.8},
  {rank: 139, name: "Steven Stamkos", team: "NSH", pos: "C,LW,RW", avg: 133.2},
  {rank: 140, name: "Owen Tippett", team: "PHI", pos: "LW,RW", avg: 133.8},
  {rank: 141, name: "Tomas Hertl", team: "VGK", pos: "C,LW", avg: 134.8},
  {rank: 142, name: "Will Smith", team: "SJ", pos: "C,RW", avg: 136.8},
  {rank: 143, name: "Thatcher Demko", team: "VAN", pos: "G", avg: 138.2},
  {rank: 144, name: "Ryan Nugent-Hopkins", team: "EDM", pos: "C,LW", avg: 139.0},
  {rank: 145, name: "Jeremy Swayman", team: "BOS", pos: "G", avg: 139.2},
  {rank: 146, name: "Jakob Chychrun", team: "WSH", pos: "D", avg: 141.8},
  {rank: 147, name: "Tyler Toffoli", team: "SJ", pos: "LW,RW", avg: 142.6},
  {rank: 148, name: "Jonathan Marchessault", team: "NSH", pos: "RW", avg: 142.8},
  {rank: 149, name: "Noah Dobson", team: "MTL", pos: "D", avg: 143.0},
  {rank: 150, name: "Joey Daccord", team: "SEA", pos: "G", avg: 143.6},
  {rank: 151, name: "John Carlson", team: "WSH", pos: "D", avg: 144.0},
  {rank: 152, name: "Jackson Lacombe", team: "ANA", pos: "D", avg: 144.2},
  {rank: 153, name: "Brock Boeser", team: "VAN", pos: "RW", avg: 145.2},
  {rank: 154, name: "Charlie McAvoy", team: "BOS", pos: "D", avg: 145.6},
  {rank: 155, name: "Pavel Buchnevich", team: "STL", pos: "C,LW,RW", avg: 147.0},
  {rank: 156, name: "Patrick Kane", team: "DET", pos: "RW", avg: 147.0},
  {rank: 157, name: "Brock Nelson", team: "COL", pos: "C", avg: 147.4},
  {rank: 158, name: "Marco Kasper", team: "DET", pos: "C,LW", avg: 149.8},
  {rank: 159, name: "Leo Carlsson", team: "ANA", pos: "C", avg: 150.0},
  {rank: 160, name: "Will Cuylle", team: "NYR", pos: "LW,RW", avg: 150.0},
  {rank: 161, name: "Brad Marchand", team: "FLA", pos: "LW", avg: 150.2},
  {rank: 162, name: "Lukas Dostal", team: "ANA", pos: "G", avg: 151.4},
  {rank: 163, name: "Alexis Lafrenière", team: "NYR", pos: "LW,RW", avg: 151.6},
  {rank: 164, name: "Jonathan Huberdeau", team: "CGY", pos: "C,LW", avg: 152.6},
  {rank: 165, name: "Cutter Gauthier", team: "ANA", pos: "LW", avg: 152.8},
  {rank: 166, name: "Mason McTavish", team: "ANA", pos: "C", avg: 154.6},
  {rank: 167, name: "John Gibson", team: "DET", pos: "G", avg: 155.2},
  {rank: 168, name: "Dylan Cozens", team: "OTT", pos: "C", avg: 156.0},
  {rank: 169, name: "Shayne Gostisbehere", team: "CAR", pos: "D", avg: 156.6},
  {rank: 170, name: "Chris Kreider", team: "ANA", pos: "LW", avg: 157.4},
  {rank: 171, name: "Luke Hughes", team: "NJ", pos: "D", avg: 157.4},
  {rank: 172, name: "Joseph Woll", team: "TOR", pos: "G", avg: 158.4},
  {rank: 173, name: "Sean Monahan", team: "CBJ", pos: "C", avg: 159.0},
  {rank: 174, name: "Vince Dunn", team: "SEA", pos: "D", avg: 160.4},
  {rank: 175, name: "Matt Coronato", team: "CGY", pos: "RW", avg: 161.2},
  {rank: 176, name: "Evgeni Malkin", team: "PIT", pos: "C,LW", avg: 163.2},
  {rank: 177, name: "Kent Johnson", team: "CBJ", pos: "C,LW,RW", avg: 163.8},
  {rank: 178, name: "Erik Karlsson", team: "PIT", pos: "D", avg: 164.0},
  {rank: 179, name: "Artturi Lehkonen", team: "COL", pos: "LW,RW", avg: 165.2},
  {rank: 180, name: "Gabriel Landeskog", team: "COL", pos: "LW", avg: 165.6},
  {rank: 181, name: "Pierre-Luc Dubois", team: "WSH", pos: "C,LW", avg: 165.6},
  {rank: 182, name: "Seth Jones", team: "FLA", pos: "D", avg: 165.6},
  {rank: 183, name: "Marco Rossi", team: "MIN", pos: "C", avg: 170.0},
  {rank: 184, name: "Brandon Montour", team: "SEA", pos: "D", avg: 170.6},
  {rank: 185, name: "Anze Kopitar", team: "LA", pos: "C", avg: 170.8},
  {rank: 186, name: "Morgan Geekie", team: "BOS", pos: "C,LW,RW", avg: 171.6},
  {rank: 187, name: "Ryan Donato", team: "CHI", pos: "C,LW,RW", avg: 172.2},
  {rank: 188, name: "Morgan Rielly", team: "TOR", pos: "D", avg: 175.8},
  {rank: 189, name: "William Eklund", team: "SJ", pos: "LW", avg: 176.0},
  {rank: 190, name: "Nick Schmaltz", team: "UTA", pos: "C,RW", avg: 176.8},
  {rank: 191, name: "Devon Toews", team: "COL", pos: "D", avg: 178.2},
  {rank: 192, name: "Troy Terry", team: "ANA", pos: "RW", avg: 184.4},
  {rank: 193, name: "Aliaksei Protas", team: "WSH", pos: "LW,RW", avg: 185.2},
  {rank: 194, name: "Claude Giroux", team: "OTT", pos: "LW,RW", avg: 185.2},
  {rank: 195, name: "Logan Stankoven", team: "CAR", pos: "C,RW", avg: 185.4},
  {rank: 196, name: "Josh Norris", team: "BUF", pos: "C", avg: 187.0},
  {rank: 197, name: "Drew Doughty", team: "LA", pos: "D", avg: 188.0},
  {rank: 198, name: "Tyler Seguin", team: "DAL", pos: "C,RW", avg: 189.2},
  {rank: 199, name: "Cole Perfetti", team: "WPG", pos: "C,LW,RW", avg: 189.6},
  {rank: 200, name: "Dmitri Voronkov", team: "CBJ", pos: "LW", avg: 190.2},
  {rank: 201, name: "Connor McMichael", team: "WSH", pos: "LW", avg: 190.6},
  {rank: 202, name: "Jimmy Snuggerud", team: "STL", pos: "RW", avg: 180.3},
  {rank: 203, name: "Ivan Barbashev", team: "VGK", pos: "LW", avg: 195.2},
  {rank: 204, name: "Anton Lundell", team: "FLA", pos: "C", avg: 181.3},
  {rank: 205, name: "Jake DeBrusk", team: "VAN", pos: "LW,RW", avg: 196.4},
  {rank: 206, name: "Kiefer Sherwood", team: "VAN", pos: "RW", avg: 196.8},
  {rank: 207, name: "Jackson Blake", team: "CAR", pos: "RW", avg: 198.2},
  {rank: 208, name: "Zeev Buium", team: "MIN", pos: "D", avg: 185.8},
  {rank: 209, name: "Tony DeAngelo", team: "NYI", pos: "D", avg: 200.0},
  {rank: 210, name: "Sam Rinzel", team: "CHI", pos: "D", avg: 200.8},
  {rank: 211, name: "Conor Garland", team: "VAN", pos: "RW", avg: 201.0},
  {rank: 212, name: "Aaron Ekblad", team: "FLA", pos: "D", avg: 201.8},
  {rank: 213, name: "Brayden Schenn", team: "STL", pos: "C", avg: 202.6},
  {rank: 214, name: "Ukko-Pekka Luukkonen", team: "BUF", pos: "G", avg: 204.2},
  {rank: 215, name: "Andrei Kuzmenko", team: "LA", pos: "LW,RW", avg: 205.4},
  {rank: 216, name: "Jeff Skinner", team: "SJ", pos: "LW", avg: 194.3},
  {rank: 217, name: "Elias Lindholm", team: "BOS", pos: "C", avg: 206.2},
  {rank: 218, name: "Brock Faber", team: "MIN", pos: "D", avg: 196.8},
  {rank: 219, name: "Anthony Cirelli", team: "TB", pos: "C", avg: 208.2},
  {rank: 220, name: "Thomas Chabot", team: "OTT", pos: "D", avg: 198.5},
  {rank: 221, name: "Frank Vatrano", team: "ANA", pos: "C,LW", avg: 198.5},
  {rank: 222, name: "Trevor Zegras", team: "PHI", pos: "C", avg: 199.8},
  {rank: 223, name: "Gustav Forsling", team: "FLA", pos: "D", avg: 200.8},
  {rank: 224, name: "Noah Hanifin", team: "VGK", pos: "D", avg: 212.0},
  {rank: 225, name: "Frank Nazar", team: "CHI", pos: "C", avg: 202.3},
  {rank: 226, name: "Zayne Parekh", team: "CGY", pos: "D", avg: 190.7},
  {rank: 227, name: "Mason Marchment", team: "SEA", pos: "LW", avg: 206.5},
  {rank: 228, name: "Evander Kane", team: "VAN", pos: "LW", avg: 207.5},
  {rank: 229, name: "Matty Beniers", team: "SEA", pos: "C", avg: 218.4},
  {rank: 230, name: "Anders Lee", team: "NYI", pos: "LW", avg: 219.0},
  {rank: 231, name: "Jet Greaves", team: "CBJ", pos: "G", avg: 212.3},
  {rank: 232, name: "Spencer Knight", team: "CHI", pos: "G", avg: 214.0},
  {rank: 233, name: "Pavel Zacha", team: "BOS", pos: "C,LW", avg: 214.5},
  {rank: 234, name: "Cam Fowler", team: "STL", pos: "D", avg: 202.3},
  {rank: 235, name: "Rasmus Andersson", team: "CGY", pos: "D", avg: 206.3},
  {rank: 236, name: "Mackie Samoskevich", team: "FLA", pos: "RW", avg: 218.0},
  {rank: 237, name: "Shane Wright", team: "SEA", pos: "C", avg: 224.8},
  {rank: 238, name: "Ryan Leonard", team: "WSH", pos: "RW", avg: 218.3},
  {rank: 239, name: "Darnell Nurse", team: "EDM", pos: "D", avg: 210.7},
  {rank: 240, name: "Boone Jenner", team: "CBJ", pos: "C,LW", avg: 213.7},
  {rank: 241, name: "Patrik Laine", team: "MTL", pos: "LW,RW", avg: 228.8},
  {rank: 242, name: "Jiri Kulich", team: "BUF", pos: "C", avg: 223.5},
  {rank: 243, name: "Jamie Benn", team: "DAL", pos: "C,LW", avg: 225.5},
  {rank: 244, name: "Ryan O'Reilly", team: "NSH", pos: "C", avg: 225.5},
  {rank: 245, name: "Alexander Nikishin", team: "CAR", pos: "D", avg: 217.7},
  {rank: 246, name: "Isaac Howard", team: "EDM", pos: "LW", avg: 231.0},
  {rank: 247, name: "Matias Maccelli", team: "TOR", pos: "LW", avg: 227.0},
  {rank: 248, name: "Warren Foegele", team: "LA", pos: "LW,RW", avg: 203.0},
  {rank: 249, name: "Oliver Bjorkstrand", team: "TB", pos: "RW", avg: 232.6},
  {rank: 250, name: "Neal Pionk", team: "WPG", pos: "D", avg: 206.5},
  {rank: 251, name: "Michael Bunting", team: "NSH", pos: "LW", avg: 221.3},
  {rank: 252, name: "Blake Coleman", team: "CGY", pos: "C,LW,RW", avg: 229.0},
  {rank: 253, name: "Jake Neighbours", team: "STL", pos: "LW,RW", avg: 232.0},
  {rank: 254, name: "Alex Laferriere", team: "LA", pos: "RW", avg: 213.5},
  {rank: 255, name: "John Klingberg", team: "SJ", pos: "D", avg: 226.7},
  {rank: 256, name: "Mikael Granlund", team: "ANA", pos: "C,LW,RW", avg: 234.3},
  {rank: 257, name: "Barrett Hayton", team: "UTA", pos: "C", avg: 229.0},
  {rank: 258, name: "Jason Zucker", team: "BUF", pos: "LW", avg: 235.0},
  {rank: 259, name: "Filip Hronek", team: "VAN", pos: "D", avg: 219.5},
  {rank: 260, name: "Charlie Lindgren", team: "WSH", pos: "G", avg: 236.0},
  {rank: 261, name: "Simon Holmstrom", team: "NYI", pos: "RW", avg: 192.0},
  {rank: 262, name: "Teuvo Teravainen", team: "CHI", pos: "LW,RW", avg: 222.0},
  {rank: 263, name: "Matthew Schaefer", team: "NYI", pos: "D", avg: 233.3},
  {rank: 264, name: "Michael Misa", team: "SJ", pos: "C", avg: 225.5},
  {rank: 265, name: "Samuel Ersson", team: "PHI", pos: "G", avg: 225.5},
  {rank: 266, name: "Kris Letang", team: "PIT", pos: "D", avg: 227.0},
  {rank: 267, name: "Tristan Jarry", team: "PIT", pos: "G", avg: 235.3},
  {rank: 268, name: "Mats Zuccarello", team: "MIN", pos: "RW", avg: 236.0},
  {rank: 269, name: "Maxim Shabanov", team: "NYI", pos: "RW", avg: 240.5},
  {rank: 270, name: "Bobby McMann", team: "TOR", pos: "LW", avg: 238.0},
  {rank: 271, name: "Yegor Sharangovich", team: "CGY", pos: "C,LW,RW", avg: 213.0},
  {rank: 272, name: "Bowen Byram", team: "BUF", pos: "D", avg: 232.5},
  {rank: 273, name: "Casey Mittelstadt", team: "BOS", pos: "C", avg: 239.0},
  {rank: 274, name: "William Karlsson", team: "VGK", pos: "C", avg: 244.0},
  {rank: 275, name: "Mattias Ekholm", team: "EDM", pos: "D", avg: 234.0},
  {rank: 276, name: "Jake Walman", team: "EDM", pos: "D", avg: 234.0},
  {rank: 277, name: "Sean Couturier", team: "PHI", pos: "C", avg: 218.0},
  {rank: 278, name: "Mikael Backlund", team: "CGY", pos: "C", avg: 224.0},
  {rank: 279, name: "Jonathan Drouin", team: "NYI", pos: "LW,RW", avg: 238.0},
  {rank: 280, name: "Phillip Danault", team: "LA", pos: "C", avg: 225.0},
  {rank: 281, name: "Calvin Pickard", team: "EDM", pos: "G", avg: 238.5},
  {rank: 282, name: "Bobby Brink", team: "PHI", pos: "RW", avg: 228.0},
  {rank: 283, name: "Max Domi", team: "TOR", pos: "C,LW", avg: 240.5},
  {rank: 284, name: "Tyson Foerster", team: "PHI", pos: "LW,RW", avg: 246.0},
  {rank: 285, name: "Justin Faulk", team: "STL", pos: "D", avg: 231.0},
  {rank: 286, name: "Owen Power", team: "BUF", pos: "D", avg: 231.0},
  {rank: 287, name: "Brent Burns", team: "COL", pos: "D", avg: 232.0},
  {rank: 288, name: "Connor Zary", team: "CGY", pos: "C,LW,RW", avg: 232.0},
  {rank: 289, name: "Evan Rodrigues", team: "FLA", pos: "C,LW,RW", avg: 233.0},
  {rank: 290, name: "Nick Paul", team: "TB", pos: "C,LW", avg: 234.0},
  {rank: 291, name: "Zack Bolduc", team: "MTL", pos: "RW", avg: 246.0},
  {rank: 292, name: "Stefan Noesen", team: "NJ", pos: "LW,RW", avg: 239.0},
  {rank: 293, name: "Dan Vladar", team: "PHI", pos: "G", avg: 241.0},
  {rank: 294, name: "Trevor Moore", team: "LA", pos: "LW,RW", avg: 241.0},
  {rank: 295, name: "Jordan Eberle", team: "SEA", pos: "RW", avg: 248.0},
  {rank: 296, name: "Colton Parayko", team: "STL", pos: "D", avg: 247.0},
  {rank: 297, name: "Luke Evangelista", team: "NSH", pos: "RW", avg: 247.0},
  {rank: 298, name: "Brandt Clarke", team: "LA", pos: "D", avg: 248.3},
  {rank: 299, name: "Mavrik Bourque", team: "DAL", pos: "C,RW", avg: 248.0},
  {rank: 300, name: "Danila Yurov", team: "MIN", pos: "RW", avg: 248.0}
]

// Helper functions for player data
export const normalizeName = (name: string): string => {
  const nameAliases: Record<string, string> = { 
    'jt miller': 'j.t. miller', 
    'tim stutzle': 'tim stützle', 
    'jj peterka': 'jj peterka', 
    'adam fantili': 'adam fantilli' 
  }
  const normalized = name.toLowerCase().replace(/[^\w\s]/g, '').replace(/\s+/g, ' ').trim()
  return nameAliases[normalized] || normalized
}

export const playersByName = new Map(
  playerRankings.map(p => [normalizeName(p.name), p])
)

export const findPlayerByName = (inputName: string): Player | undefined => {
  return inputName ? playersByName.get(normalizeName(inputName)) : undefined
}

export const getPlayerPrimaryPosition = (player: Player): string => {
  if (!player || !player.pos) return 'C'
  if (player.pos.includes('G')) return 'G'
  if (player.pos.includes('D')) return 'D'
  if (player.pos.includes('C')) return 'C'
  if (player.pos.includes('LW')) return 'LW'
  if (player.pos.includes('RW')) return 'RW'
  return 'C' // Default fallback
}
